# Generated by Django 4.1.2 on 2023-02-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
