# Generated by Django 4.1.2 on 2023-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sign_ids', models.CharField(max_length=100)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('last_sign_index', models.IntegerField(default=0)),
            ],
        ),
    ]
