# Generated by Django 4.1.2 on 2023-02-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SignList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signs', models.ManyToManyField(to='quiz.sign')),
            ],
        ),
        migrations.CreateModel(
            name='UserSignList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('last_sign_index', models.IntegerField(default=0)),
                ('sign_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.signlist')),
            ],
        ),
    ]
