# Generated by Django 4.1.2 on 2023-06-09 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizlist',
            name='last_practiced',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
