# Generated by Django 4.1.2 on 2023-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='video_url',
            field=models.CharField(max_length=100),
        ),
    ]
