# Generated by Django 4.1.2 on 2023-03-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_signlist_quizlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='name',
            new_name='sign_name',
        ),
    ]
