name: Code coverage

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install django_coverage_plugin
    - name: Run code coverage
      run: |
        coverage erase
        coverage run manage.py test
        coverage report
