name: Code coverage

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -r django/requirements.txt
        pip install coverage
    - name: Run code coverage
      run: |
        coverage run  django/manage.py test
        coverage report --fail-under=80
