name: Pylint

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install -r django/requirements.txt
          pip install pylint
          pip install pylint-django
      - name: Analysing the code with pylint
        run: |
          env/bin/pylint --load-plugin=pylint_django --ignore-patterns="wsgi|asgi|apps|\d{4}_initial|manage" --disable=E0401 django
